ALTER TABLE quiz_leads
  ADD COLUMN IF NOT EXISTS tempo_quiz      INTEGER,
  ADD COLUMN IF NOT EXISTS chegou_resultado BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_final        BOOLEAN DEFAULT FALSE;
